version: '2.6'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    env_file:
      - .env

  backend:
    build:
        context: .
        dockerfile: Dockerfile

    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis_data: